export enum Techs {
  HTML = 'HTML',
  CSS = 'CSS',
  JS = 'Javascript',
  Vue = 'Vue (Vuex and VueRouter)',
  TS = 'TypeScript',
  React = 'React',
  Sass = 'Sass',
  Vuetify = 'Vuetify',
  Jest = 'Jest',
  RA = 'React-admin',
  Nx = 'Nx',
  AD = 'Azure DevOps',
  AS = 'App Service',
  SWA = 'Static Web Apps',
  Amplify = 'Amplify',
  GHA = 'GitHub Actions',
  Sentry = 'Sentry',
  SC = 'Sonar Cloud',
  Akamai = 'Akamai',
  SA = 'Storage Account',
  Vite = 'Vite',
  Nuxt = 'Nuxt',
}
